### ISSUE TITLE
test-gameversion doesn't check if incompatible mods are enabled

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/test-gameversion#3]
https://github.com/Nexus-Mods/test-gameversion/blob/ab5261234f1b3049539d98c8cd1048a17ce39d54/src/index.ts#L6

Should this check the mod is enabled before reporting as incompatible?

**Comment by TanninOne** [comment]
a) please create all issues in Nexus-Mods/Vortex, I don't want to have to monitor > 60 issue trackers
b) please avoid being indirect with your report. If you have a problem, report the problem. If you don't have a problem, what brought you to that line?
c) I would argue that no, the check doesn't have to check if the mod is enabled. The mod is _installed_ and thus may be enabled in a profile. It could be quite annoying if you have to toggle between every profile to find if the game update broke a mod in any of them.
Our mod update check also doesn't only check enabled mods for updates.
